/**
 * Pure validation for the bib visual editor.
 *
 * The "Check" button (reviewer requirement) validates only — it never writes.
 *
 * Rules (per reviewer / Patashnik btxdoc, see docs/sources/bib-format-notes.md):
 *  - citation key required for EXISTING entries, format-checked; for new
 *    entries it is autogenerated at materialize time (not checked here).
 *  - required fields: standalone "X is required"; OR-group "Either A or B is
 *    required" shown next to EVERY empty member of the group.
 *  - format checks for filled values: year (4 digits), DOI, URL.
 *
 * validateEntry() is pure: it returns machine-readable messages
 * (ValidationMessage), the view renders them via i18n.
 */
import { getEntryType } from './bib-types'

export type ValidationMessage =
  | {
      kind: 'id-required'
    }
  | {
      kind: 'id-invalid'
    }
  | {
      /** One empty standalone required field, or a whole empty OR-group */
      kind: 'required-missing'
      /** Field member(s) this message applies to (standalone: 1) */
      labelFields: string[]
      group: boolean
    }
  | {
      kind: 'year-format'
    }
  | {
      kind: 'doi-format'
    }
  | {
      kind: 'url-invalid'
  }

export type ValidationResult = {
  /** Validation messages keyed by field name (shown under each listed field) */
  byField: Record<string, ValidationMessage>
  /** True when validation passed */
  valid: boolean
}

/**
 * Validate an entry draft.
 *
 * kind 'existing': citation key required + format-checked.
 * kind 'new': citation key check only if the user typed something; otherwise
 * the key is autogenerated at materialize time.
 */
export function validateEntry(
  entry: { type: string; id: string; fields: Record<string, string> },
  kind: 'existing' | 'new'
): ValidationResult {
  const typeDef = getEntryType(entry.type)
  const required = typeDef?.requiredFields || []
  const byField: Record<string, ValidationMessage> = {}

  // 1) citation key
  if (kind === 'existing' || entry.id.trim()) {
    if (!entry.id.trim()) {
      byField.id = { kind: 'id-required' }
    } else if (!/^[A-Za-z0-9_:.\-/]+$/.test(entry.id.trim())) {
      byField.id = { kind: 'id-invalid' }
    }
  }

  // 2) required fields (OR-group semantics)
  // A group message is attached to every empty member of an empty group.
  for (const req of required) {
    const members: string[] = Array.isArray(req) ? [...req] : [req]
    const allEmpty = members.every(f => !entry.fields[f]?.trim())
    if (!allEmpty) continue
    const group = Array.isArray(req)
    // skip members that have a more specific message already (e.g. format)
    for (const f of members) {
      if (f in byField) continue
      byField[f] = {
        kind: 'required-missing',
        labelFields: members,
        group,
      }
    }
  }

  // 3) format checks (only for filled values)
  const f = entry.fields
  if (f.year && !/^\d{4}$/.test(f.year.trim()) && !('year' in byField)) {
    byField.year = { kind: 'year-format' }
  }
  if (f.doi && !/^10\.\d{4,9}\/\S+$/.test(f.doi.trim()) && !('doi' in byField)) {
    byField.doi = { kind: 'doi-format' }
  }
  if (f.url && !(f.url in byField || byField.url)) {
    try {
      new URL(f.url.trim())
    } catch {
      byField.url = { kind: 'url-invalid' }
    }
  }

  return { byField, valid: Object.keys(byField).length === 0 }
  // (per-field stars are computed by bib-types.requiredStarMembers in the
  //  form view; the messages above are for the Check button only)
}
