services:
  git-bridge:
    restart: always
    image: quay.io/sharelatex/git-bridge:6.1.2 
    volumes:
        - ./data:/data/git-bridge
    container_name: git-bridge
    expose:
        - "8000"
    environment:
        GIT_BRIDGE_API_BASE_URL: "http://overleaf:3000/api/v0/" 
        GIT_BRIDGE_OAUTH2_SERVER: "http://overleaf"
        GIT_BRIDGE_POSTBACK_BASE_URL: "http://git-bridge:8000"
        GIT_BRIDGE_ROOT_DIR: "/data/git-bridge"
    user: root
    command: ["/server-pro-start.sh"]

    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s